<?php
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Http\Requests\StoreTorrentRequest;

beforeEach(function (): void {
    $this->subject = new StoreTorrentRequest();
});

test('authorize', function (): void {
    $actual = $this->subject->authorize();

    expect($actual)->toBeTrue();
});

test('rules', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'torrent' => [
            'required',
            'file',
            'mimes:torrent',
            'mimetypes:application/x-bittorrent',
        ],
        'name' => [
            'required',
            'unique:torrents',
            'max:255',
        ],
        'description' => [
            'required',
            'max:4294967296',
        ],
        'mediainfo' => [
            'nullable',
            'sometimes',
            'max:4294967296',
        ],
        'bdinfo' => [
            'nullable',
            'sometimes',
            'max:4294967296',
        ],
        'category_id' => [
            'required',
            'exists:categories,id',
        ],
        'type_id' => [
            'required',
            'exists:types,id',
        ],
        'resolution_id' => [
            'exists:resolutions,id',
        ],
        'region_id' => [
            'nullable',
            'exists:regions,id',
        ],
        'distributor_id' => [
            'nullable',
            'exists:distributors,id',
        ],
        'imdb' => [
        ],
        'tvdb' => [
        ],
        'tmdb' => [
        ],
        'mal' => [
        ],
        'igdb' => [
        ],
        'season_number' => [
        ],
        'episode_number' => [
        ],
        'anon' => [
            'required',
            'boolean',
        ],
        'stream' => [
            'required',
            'boolean',
        ],
        'sd' => [
            'required',
            'boolean',
        ],
        'personal_release' => [
            'required',
            'boolean',
        ],
        'internal' => [
            'sometimes',
            'boolean',
        ],
        'free' => [
            'sometimes',
            'integer',
            'numeric',
            'between:0,100',
        ],
        'refundable' => [
            'sometimes',
            'boolean',
        ],
    ], $actual);
});

test('messages', function (): void {
    $actual = $this->subject->messages();

    expect($actual)->toEqual([
        'igdb.in'                 => "如果媒体不存在于IGDB上或您未上传游戏，IGDB ID必须为0。",
        'tmdb.in'                 => "如果媒体不存在于TMDB上或您未上传电视节目或电影，TMDB ID必须为0。",
        'imdb.in'                 => "如果媒体不存在于IMDB上或您未上传电视节目或电影，IMDB ID必须为0。",
        'tvdb.in'                 => "如果媒体不存在于TVDB上或您未上传电视节目，TVDB ID必须为0。",
        'mal.in'                  => "如果媒体不存在于MAL上或您未上传电视或电影，MAL ID必须为0。",
        'region_id.required'      => '请选择小说分类',
        'distributor_id.required' => '请选择音乐风格',
    ]);
});
